project:
  type: website

website:
  open-graph: true
  title: "39 North Labs, LLC."
  site-url: https://39n.io
  favicon: favicon.png
  twitter-card:
    creator: "@gavroz"
  navbar:
    search: true
    title: " "
    logo: logo.png
    left:
      - index.qmd
      - services.qmd
      - open-source.qmd
      - platforms.qmd
      - about.qmd


format:
  html:
    theme: cerulean
    css: styles.css
    toc: false


