project:
  type: website

website:
  open-graph: true
  title: "39 North Labs, LLC."
  description: "Data Science, GIS & Business Analytics Consulting"
  site-url: https://39n.io
  body-footer: | 
    Copyright © 2023 **39 North Labs LLC.** 610 Lacey Road, #1232 Forked River, NJ 08731 - [Privacy Policy](https://39n.io/privacy-policy)
  favicon: favicon.png
  twitter-card:
    creator: "@gavroz"
  navbar:
    search: true
    title: " "
    logo: logo.png
    left:
      - index.qmd
      - services.qmd
      - open-source.qmd
      - blog.qmd
      - about.qmd


format:
  html:
    email-obfuscation: javascript
    theme: lux
    css: styles.css
    toc: false


