project:
  type: website

website:
  open-graph: true
  title: "39 North Analytics"
  site-url: https://39n.io
  favicon: favicon.png
  twitter-card:
    creator: "@gavroz"
  navbar:
    left:
      - index.qmd
      - services.qmd
      - open-source.qmd
      - platforms.qmd
      - about.qmd


format:
  html:
    theme: cosmo
    css: styles.css
    toc: false


