project:
  type: website

website:
  open-graph: true
  title: "39 North Labs, LLC."
  description: "Data Science, GIS & Business Analytics Consulting"
  site-url: https://39n.io
  body-footer: | 
    Copyright © 2023 39 North Labs LLC. 610 Lacey Road #1232 Forked River, NJ 08731
  favicon: favicon.png
  twitter-card:
    creator: "@gavroz"
  navbar:
    search: true
    title: " "
    logo: logo.png
    left:
      - index.qmd
      - services.qmd
      - open-source.qmd
      - about.qmd


format:
  html:
    theme: cerulean
    css: styles.css
    toc: false


