---
title: "About"
---

39 North Labs LLC is a boutique consulting firm that specializes in providing professional data analytics and consulting services. Our name, 39 North Labs, is inspired by the [39th parallel north](https://en.wikipedia.org/wiki/39th_parallel_north), a circle of latitude that stretches across the globe and includes areas of New Jersey. This name reflects our focus on spatial data science, our local roots in New Jersey, and our global vision to provide thought leadership and expertise to our clients and the wider data community.

## What We Do

We provide consulting services, custom programming, and educational/training services for private, public sector, and individual clients. We also develop widely used [open-source software](/open-source.qmd) packages for data science and related programming languages. These packages have been adopted by businesses, higher education, and individuals working with geospatial data for research and business/clinical use cases. Our services leverage our expertise in advanced analytics and informatics tools to create value for our clients.

## What Makes Us Different

What sets us apart from other consulting firms is our unique ability to solve complex problems with data. We have a deep understanding of the latest data science techniques and technologies, and we're able to apply this knowledge to deliver real-world solutions that drive results for our clients. We are dedicated to staying at the forefront of emerging technologies, and we're constantly pushing the boundaries of what's possible with data.

## Our Team

The firm is led by principal and owner, [Gavin Rozzi](/gavin-rozzi.qmd), who has over a decade of experience in technology consulting, platform development & data science. Our team is composed of experts in data analytics, informatics, spatial analysis, and GIS/mapping who are dedicated to delivering valuable insights and driving results for our clients. 
