---
title: "Home"
page-layout: full
toc: false
---

# Data Science, GIS & Business Analytics Consulting 

Welcome to 39 North Labs, LLC – a boutique consultancy that specializes in providing [professional services](/services.qmd) leveraging data analytics, informatics, spatial analysis, and GIS / mapping. We help organizations and businesses make data-driven decisions through our expertise in these areas.

Our team of highly skilled professionals has a wealth of experience as well as a passion for developing innovative solutions to complex problems. We pride ourselves on delivering high-quality, customized services that meet the unique needs of our clients.

In addition to providing top-notch consulting services, we also develop [open-source software packages](/open-source.qmd) to advance the state of the art in data science. Our packages are widely used in business, academia and government and have been designed to be user-friendly and intuitive, making it easy for professionals and organizations to leverage the power of data analysis and visualization.

Whether you need help with data analytics, informatics or GIS, 39 North Labs has the expertise and resources to help your business succeed. 

Contact us today to learn more about how we can help you make better data-driven decisions.

Email [gavin@39n.io](mailto:gavin@39n.io) schedule an introductory call.


