---
title: "Privacy Policy"
page-layout: full
toc: true
---

## Introduction
39 North Labs, LLC (“39 North Labs,” “we,” or “us”) is committed to protecting the privacy of our website visitors and clients. This Privacy Policy (“Policy”) applies to the 39 North Labs, LLC. website ("https://39n.io") and governs the collection, use, and disclosure of personal information that we collect from users of our website, as well as any social media platforms operated by us.

By using our website, you consent to the data practices described in this Policy. If you do not agree with the data practices described in this Policy, you should not use our website. We reserve the right to change this Policy at any time, and will inform you of any changes through the website or via email. Your continued use of our website following the posting of changes to this Policy will be deemed your acceptance of those changes.

## Information We Collect:
We may collect personal information from you, including but not limited to your name, address, telephone number, email address, and any other information you provide to us. We may also automatically collect certain information about your use of our website, including but not limited to your IP address, browser type, and the pages you visit.

## Use of Information:
We may use your personal information to provide you with information, products or services that you request, to contact you with information about our company and our products and services, or to improve our website and our products and services. We will only use your personal information for the purposes for which it was collected and will not use it for any other legal purpose without your consent.

## Disclosure of Information:
We may disclose your personal information to any of our affiliates, or to our partners or other third parties for the purposes for which it was collected and in compliance with legal regulations. We may also disclose your personal information to any third party if we believe in good faith that we are required to do so by law.

## Security of Information:
We use reasonable security measures to protect against unauthorized access to or unauthorized alteration, disclosure or destruction of data. We restrict access to your personal information to our employees, contractors, and agents who need to know that information in order to operate, develop or improve our website and services.

## Data Retention:
We will retain your personal information for as long as necessary to provide you with the products and services you have requested, or for other legal purposes.

## Third-Party Sharing:
We may share your personal information with third parties for the purpose of providing you with the products and services you have requested. We will not share your personal information with third parties for marketing or other purposes without your consent.

## Compliance with Data Protection Laws:
We are committed to complying with all relevant data protection laws and regulations as they may apply within the State of New Jersey.